### ISSUE TITLE
plugin seems to have stopped working with newest homebridge?!

### ISSUE THREAD

**Issue by lightz22** [rainlake/homebridge-platform-lightify#27]
Hi! been using this plugin and worked great with homebridge and my osram gateway and light strips, but it just stopped working and the message is saying "homebridge is having trouble starting" due to this plugin...any chance you could check this?
Thanks!

**Comment by dalethomas81** [comment]
When is the last time you restarted it before this happened? Can you reach it via the Lightify app? Are you aware the cloud servers were turned off some time ago? Personally, I have migrated to a Hubitat hub but you may want to look at other products. 

https://www.osram.com/cb/lightify/index.jsp

**Comment by mpick060726** [comment]
Anyone still using this plugin?  Since upgrading Homebridge to the 2.x version, I'm getting errors "This plugin is taking long time to load and preventing Homebridge from starting. See https://homebridge.io/w/JtMGR for more info." and not sure how to resolve.  I think the following is the necessary aspects of the log file from the plugin if someone with some programming knowledge can assist.

[6/7/2026, 7:24:54 PM] [Lightify] Initializing Lightify platform...
[6/7/2026, 7:24:54 PM] [Lightify] Initializing child bridge <redacted>
Setup Payload:
X-HM://<redacted>
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    <redacted>
                       
[6/7/2026, 7:24:54 PM] Homebridge v2.1.0 (HAP v2.1.7) (Homebridge <redacted>) is running on port 51816.
[6/7/2026, 7:24:54 PM] [Lightify] Child bridge starting (pid 82628)...
[6/7/2026, 7:24:55 PM] [Lightify] Child bridge started successfully (plugin v0.3.7).
[6/7/2026, 7:24:55 PM] [Lightify] Lightify Light [Front Entry]
[6/7/2026, 7:24:55 PM] [Lightify] Discovered failed TypeError: Class constructor Service cannot be invoked without 'new'
    at new Lightbulb (/usr/local/lib/node_modules/homebridge-platform-lightify/index.js:14:17)
    at new LightifyAccessory (/usr/local/lib/node_modules/homebridge-platform-lightify/index.js:224:20)
    at /usr/local/lib/node_modules/homebridge-platform-lightify/index.js:197:44
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-platform-lightify/index.js:194:21
    at tryCallOne (/usr/local/lib/node_modules/homebridge-platform-lightify/node_modules/promise/lib/core.js:37:12)
    at /usr/local/lib/node_modules/homebridge-platform-lightify/node_modules/promise/lib/core.js:123:15
    at flush (/usr/local/lib/node_modules/homebridge-platform-lightify/node_modules/asap/raw.js:50:29)
    at processTicksAndRejections (node:internal/process/task_queues:85:11)

**Comment by devenbj** [comment]
The platform went end of life in 2021. I'm impressed it worked so long for you. I migrated my Lightify devices to Hubitat before the shutdown. Hubitat has native HomeKit support. They've continued working for me via Hubitat.

**Comment by mpick060726** [comment]
> The platform went end of life in 2021. I'm impressed it worked so long for you. I migrated my Lightify devices to Hubitat before the shutdown. Hubitat has native HomeKit support. They've continued working for me via Hubitat.

yes, and they (Osram) updated the firmware for the devices to work locally before the platform went down.  I'm not really interested in spending $165 for another hub for a couple smart bulbs and smart outlets that I'd prefer to have integrated into Homekit as I can still use the Lightify app if need be.

**Comment by dalethomas81** [comment]
If you aren’t interested in moving with the technology then you should revert to the version of Homebridge that worked for you. 

Seems like if you only have a couple of bulbs that you also have the option purchase some new bulbs.
